baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Zafar Abdul Razzaq"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Zafar Scrap"
  description: "Zafar Scrap is your trusted partner in responsible Scrap management and recycling solutions."
  images: 
    - "./images/logo.png"

  logo: "./images/logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    tiktok: "https://www.tiktok.com/@mr.usmanzafar?_t=8fiWe7MiWp7&_r=1"
    instagram: "https://instagram.com/mr.usmanzafar_?igshid=NzZlODBkYWE4Ng=="
    facebook: "https://www.facebook.com/profile.php?id=100014737745386&mibextid=ZbWKwL"
    whatsapp: "https://wa.me/+971556755256"

  location:
    - "United Arab Emirates"

  contact:
    - "zafaruae@ymail.com"

  number:
    - "0556755256"
    - "0554244966"

  copyright: "© 2022 Zafar Scrap All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

  # buttons:
  #   - name: "Book a call"
  #     url: "/#"
  #     weight: 5
  #     pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"
